[package]
name = "rust-users"
version = "0.0.1"
authors = ["Abey Onalaja"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
mongodb = "*"
bson = "*"
rustc-serialize = "*"